
batch_size:
  desc: Batch size
  value: 16
epochs:
  desc: Max epochs to train for
  value: 1000
lr:
  desc: Learning rate
  value: 0.00005
patience_scheduler:
  value: 1000
emb_dim:
  desc: Projection dimension
  value: 512
hidden_dims_text_embedder: 
  desc: Hidden dims
  value: [128,128,128]
text_features_path:
  desc: Path to precomputed text features pt file
  value: data/generated_features/text_features/longformer.pt

  

