
batch_size:
  desc: Batch size
  value: 256
epochs:
  desc: Max epochs to train for
  value: 1000
lr:
  desc: Learning rate
  value: 5.E-4
patience_scheduler:
  value: 1000
emb_dim:
  desc: Projection dimension
  value: 1000
hidden_dims:
  value: [1024,512,512,124]
visual_features_emb_dim:
  value: 1000
split_path:
  value: 'data/cub_splits/proposed_split3.txt'
text_features_path:
  desc: Path to precomputed text features pt file
  value: data/generated_features/text_features/multi-qa-mpnet-base-dot-v1.pt
preload_path:
  value: False
dropout:
  desc: Dropout probability in match predictor
  value: 0.5

  

